# Generated by Django 5.0.6 on 2024-05-19 00:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.BooleanField(default=False)),
                ('inclusion_date', models.DateField(default=datetime.datetime(2024, 5, 18, 21, 58, 35, 923288))),
                ('change_date', models.DateField(default=datetime.datetime(2024, 5, 18, 21, 58, 35, 923288))),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.modelbase')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('editon', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('polls.modelbase',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.modelbase')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(default=datetime.datetime(2024, 5, 18, 21, 58, 35, 949288))),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=14)),
            ],
            bases=('polls.modelbase',),
        ),
        migrations.CreateModel(
            name='PurchasesHistoric',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.modelbase')),
                ('purchase_date', models.DateField(default=datetime.datetime(2024, 5, 18, 21, 58, 35, 950288))),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.book')),
                ('customer_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.customer')),
            ],
            bases=('polls.modelbase',),
        ),
    ]
