# Generated by Django 5.0.6 on 2024-05-19 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseshistoric',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 20, 0, 11, 122257)),
        ),
        migrations.AlterField(
            model_name='modelbase',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 20, 0, 11, 96256)),
        ),
        migrations.AlterField(
            model_name='modelbase',
            name='inclusion_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 20, 0, 11, 95264)),
        ),
        migrations.AlterField(
            model_name='purchaseshistoric',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 20, 0, 11, 123257)),
        ),
    ]
