# Generated by Django 5.0.6 on 2024-06-03 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_purchaseshistoric_method_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='modelbase',
            name='change_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 23, 34, 49, 595105)),
        ),
        migrations.AlterField(
            model_name='modelbase',
            name='inclusion_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 23, 34, 49, 595105)),
        ),
        migrations.AlterField(
            model_name='purchaseshistoric',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='purchaseshistoric',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 23, 34, 49, 613057)),
        ),
    ]
